<?php
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('availabilities/css/index.css'));

$this->headTitle(_('HEAD_TITLE_DISPONIBILITES') . ' | ');
?>
<div class="page availability">
    <h1><?= _('DISPONIBILITES_TITRE') ?></h1>

    <div class="jq-tabs onglets">
            <ul id="onglets-navigation">
            <?php foreach ($this->products as $product): ?>
            <li>
                <a href="#jq-room<?= $product->id?>"><?= $product->title ?></a>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php foreach ($this->products as $product): ?>
        <div id="jq-room<?= $product->id?>" class="availability">
            <?= $product->availability?>
            <p>
                <a href="<?=
                    $this->url(
                        array(
                             'controller' => 'products',
                             'action'     => 'location',
                             'set'        => $product->url
                        ),
                        null,
                        false
                    );
                    ?>#jq-reservation">
                    <?= _('DISPONIBILITES_DEMANDE_RESERVATION') ?>
                </a>
            </p>
        </div>
        <?php endforeach; ?>
    </div>
</div>