<?php
$activity = $this->activity;
?>

<div class="activity">
    <h3>
        <?= _('HOME_ACTIVITY_TITRE') ?>
    </h3>

    <a href="<?= $this->baseUrl(); ?>activity/read/id/<?= $activity->id; ?>">
        <h4>
            <?= $activity->title ?>
        </h4>
        <p class="illustrate">
            <?php if (isset($activity->illustrations[0])): ?>
            <img
                src="<?=
                    $this->displayImage(
                        $activity->illustrations[0]->filename,
                        Llv_Constant_File_Category::ACTIVITY,
                        448,
                        9999
                    );
                    ?>"/>
            <?php else: ?>
            <img src="<?= $this->baseUrl()?>files/upload/activity/default.jpg">
            <?php endif; ?>
        </p>

        <div class="content">
            <?= $activity->content ?>
        </div>
    </a>

    <p class="more"><a href="<?= $this->baseUrl(); ?>activity"><?= _('HOME_ACTIVITY_MORE') ?></a></p>
</div>
