<?php
$activity = $this->activity;
?>

<div class="activity">
    <h3>
        <?= _('HOME_ACTIVITY_TITRE') ?>
    </h3>

    <?php if (!is_null($activity)): ?>
    <a href="<?= $this->baseUrl(); ?>activity/read/id/<?= $activity->id; ?>">
        <h4>
            <?= $activity->title ?>
        </h4>
    </a>

    <p class="illustrate">
        <a href="<?= $this->baseUrl(); ?>activity/read/id/<?= $activity->id; ?>">
            <?php if (isset($activity->illustrations[0])): ?>
            <img
                src="<?=
                    $this->displayImage(
                        $activity->illustrations[0]->filename,
                        Llv_Constant_File_Category::ACTIVITY,
                        448,
                        9999
                    );
                    ?>"/>
            <?php else: ?>
            <img src="<?= $this->baseUrl()?>files/upload/activity/default.jpg">
            <?php endif; ?>
        </a>
    </p>
    <p class="next">
        <a href="<?= $this->baseUrl(); ?>activity/read/id/<?= $activity->id; ?>">
            <?= _('HOME_ACTIVITY_NEXT') ?>
        </a>
    </p>

    <div class="content">
        <div class="content"><?= $this->shortify($activity->content, 600); ?></div>
    </div>
    <?php else: ?>
    <p class='no-result'><?= _('NEWS_LIST_NORESULT'); ?></p>
    <?php endif; ?>

    <p class="more"><a href="<?= $this->baseUrl(); ?>activity"><?= _('HOME_ACTIVITY_MORE') ?></a></p>
</div>
