<section id="activities" class="l-section">
    <div class="l-subsection color_dark"
         style="background-image:url(http://www.aravis.com/images/prestations/sitraEVE790327_199799_parapente_278.jpg);">
        <div class="l-subsection-h">
            <div class="l-subsection-hh g-html i-cf">
                <h2>
                    <?= _("HOME_ACTIVITIES_TITRE"); ?>
                </h2>
            </div>
        </div>
    </div>

    <div class="l-subsection">
        <div class="l-subsection-h">
            <div class="l-subsection-hh g-html i-cf">
                <h2 class="highlight"><?= _('HOME_ACTIVITIES_TITRE_2'); ?></h2>

                <div class="g-hr type_short"><span class="g-hr-h"><i class="fa fa-plus"></i></span></div>
                <div class="g-hr type_invisible"></div>
                <div class="g-cols">
                    <div class="one-third">
                        <div class="w-iconbox iconpos_left with_circle">
                            <div class="w-iconbox-h">
                                <a class="w-iconbox-link" href="javascript:void(0)">
                                    <div class="w-iconbox-icon">
                                        <i class="fa fa-cutlery"></i>
                                    </div>
                                    <h4 class="w-iconbox-title"><?= _('HOME_ACTIVITIES_SOUSTITRE_1'); ?></h4>
                                </a>

                                <div class="w-iconbox-text">
                                    <p><?= _('HOME_ACTIVITIES_TEXTE_1'); ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="one-third">
                        <div class="w-iconbox iconpos_left with_circle">
                            <div class="w-iconbox-h">
                                <a class="w-iconbox-link" href="javascript:void(0)">
                                    <div class="w-iconbox-icon">
                                        <i class="fa fa-road"></i>
                                    </div>
                                    <h4 class="w-iconbox-title"><?= _('HOME_ACTIVITIES_SOUSTITRE_2'); ?></h4>
                                </a>

                                <div class="w-iconbox-text">
                                    <p><?= _('HOME_ACTIVITIES_TEXTE_2'); ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="one-third">
                        <div class="w-iconbox iconpos_left with_circle">
                            <div class="w-iconbox-h">
                                <a class="w-iconbox-link" href="javascript:void(0)">
                                    <div class="w-iconbox-icon">
                                        <i class="fa fa-briefcase"></i>
                                    </div>
                                    <h4 class="w-iconbox-title"><?= _('HOME_ACTIVITIES_SOUSTITRE_3'); ?></h4>
                                </a>

                                <div class="w-iconbox-text">
                                    <p><?= _('HOME_ACTIVITIES_TEXTE_3'); ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</section>