<?php
$carrousel = $this->carrousel;
/** Carrousel */
$module = Llv_Context_Application::getInstance()->getActiveModule();
$this->headScript()->appendFile($this->buildDesignUrl('_plugin/carrousel/js/jquery.carrousel.js'));
$this->headLink()->appendStylesheet($this->buildDesignUrl('_plugin/carrousel/css/global.css'));
?>
<div class="jq-carrousel carrousel">
    <div class="slides_container">
        <?php foreach ($carrousel as $ligne): ?>
        <div class="slide">
            <a href="<?= $this->displayImage($ligne->filename, Llv_Constant_File_Category::CARROUSEL, 800, 600); ?>"
               rel="shadowbox[picture]">
                <img
                    src="<?= $this->displayImage($ligne->filename, Llv_Constant_File_Category::CARROUSEL, 580, 9999); ?>"/>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</div>