<?php
$news = $this->news;
?>

<div class="news">
    <h3>
        <?= _('HOME_NEWS_TITRE') ?>
    </h3>

    <?php if (!is_null($news)): ?>
    <a href="<?= $this->baseUrl(); ?>news/read/id/<?= $news->id; ?>">
        <h4>
            <?= $news->title ?>
        </h4>
    </a>

    <p class="illustrate">
        <a href="<?= $this->baseUrl(); ?>news/read/id/<?= $news->id; ?>">
            <?php if (isset($news->illustrations[0])): ?>
            <img
                src="<?=
                    $this->displayImage(
                        $news->illustrations[0]->filename,
                        Llv_Constant_File_Category::NEWS,
                        448,
                        9999
                    );
                    ?>"/>
            <?php else: ?>
            <img src="<?= $this->baseUrl()?>files/upload/news/default.jpg">
            <?php endif; ?>
        </a>
    </p>
    <p class="next"><a href="<?= $this->baseUrl(); ?>news/read/id/<?= $news->id; ?>"><?= _('HOME_NEWS_NEXT') ?></a></p>

    <div class="content"><?= $this->shortify($news->content, 600); ?></div>
    <?php else: ?>
    <p class='no-result'><?= _('NEWS_LIST_NORESULT'); ?></p>
    <?php endif; ?>

    <p class="more"><a href="<?= $this->baseUrl(); ?>news"><?= _('HOME_NEWS_MORE') ?></a></p>
</div>
