<?php
$module = Llv_Context_Application::getInstance()->getActiveModule();
$locale = Llv_Context_Application::getInstance()->getLocale()->toString();
/** @var $this Zend_View */

/** @var $doctype Doctype */
$doctype = new Zend_View_Helper_Doctype();
$doctype->setDoctype('HTML5');

/** Titre du site */
$this->headTitle(_('GLOBAL_HEADER_TITLE'));

/** Metas tags */
$this->headMeta()->setCharset(Llv_Config::getInstance()->project->charset);

/** Feuilles de style */
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/' . $module . '/' . $locale . '/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/' . $module . '/default/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/' . $locale . '/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/default/_common/css/global.css');

/** JS Commun */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/default/default/_common/js/common.js');
/** jQuery */
$this->headScript()->prependFile($this->baseUrl() . 'public/design/default/default/_plugin/jquery.js');
/** jQuery UI */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/default/default/_plugin/jquery-ui/js/jquery.ui.js');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/default/_plugin/jquery-ui/css/style.css');
/** ShadowBox */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/default/default/_plugin/shadowbox/shadowbox.js');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/default/_plugin/shadowbox/shadowbox.css');
/** Textarea UI */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/' . $module . '/default/_common/js/js.niceedit.js');

?>
<?php echo $this->doctype(); ?>

<html>

<head>

    <?php echo $this->headTitle(); ?>

    <?php echo $this->headMeta(); ?>

    <?php echo $this->headLink(); ?>

    <?php echo $this->headScript(); ?>
    <script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

</head>

<body>

<div id="container">
    <div id="header">
        <?php
        echo $this->partial(
            'partial/header.phtml',
            array()
        );
        ?>
    </div>
    <?php if (Llv_Context_User::getInstance()->isUserLogged()) : ?>
    <div id="menu">
        <?php
        echo $this->partial(
            'partial/menu.phtml',
            array()
        );
        ?>
    </div>
    <?php endif;?>

    <div id="wrapper"><?php echo $this->layout()->content; ?></div>

    <div id="footer">
        <?php
        echo $this->partial(
            'partial/footer.phtml',
            array()
        );
        ?>
    </div>
</div>
<script type="text/javascript">
    var i18n = <?= $this->giveJsI18nText('back');?>;
</script>

</body>

</html>