<?php
//$module = Llv_Context_Application::getInstance()->getActiveModule();
$this->headTitle(_('HEAD_TITLE_NEWS') . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('news/css/list.css'));
$this->headScript()->appendFile($this->buildDesignUrl('news/js/list.js'));
/** @var $spotlight Llv_Dto_News */
$spotlight = $this->spotlight;
$news = $this->news;
$newsPerRow = 3;
$i = 0;
?>

<h2><?= _('NEWS_LIST_TITLE'); ?></h2>

<?php if (count($spotlight) == 1): ?>
<a href="<?= $this->baseUrl(); ?>news/read/id/<?= $spotlight->id; ?>">
    <div class="spotlight">
        <div class="left">
            <h3>
                <?= $spotlight->title; ?>
            </h3>
            <?php if (isset($spotlight->illustrations[0])): ?>
            <img
                src="<?=
                    $this->displayImage(
                        $spotlight->illustrations[0]->filename,
                        Llv_Constant_File_Category::NEWS,
                        300,
                        9999
                    );
                    ?>"/>
            <?php endif; ?>
        </div>
        <div class="right">
            <p><?= $spotlight->content; ?></p>
        </div>
    </div>
</a>
<?php endif; ?>

<?php if (count($news) > 0): ?>
<div class="news">
    <ul>
        <?php foreach ($news as $newsItem): ?>
        <?php $i++; ?>
        <a href="<?= $this->baseUrl(); ?>news/read/id/<?= $newsItem->id; ?>">
            <li<?php if ($i % 3 == 0): ?> class="no-space"<?php endif; ?>>
                <div class="left">
                    <h3>
                        <?= $newsItem->title; ?>
                    </h3>
                </div>
                <div class="right">
                    <p><?= $newsItem->content; ?></p>
                </div>
            </li>
        </a>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
