<?php
//$module = Llv_Context_Application::getInstance()->getActiveModule();
$this->headTitle(_('HEAD_TITLE_NEWS') . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('news/css/list.css'));
$this->headScript()->appendFile($this->buildDesignUrl('news/js/list.js'));
$news = $this->news;
$newsPerRow = 3;
$i = 0;
?>

<div class="page">

    <h2><?= _('NEWS_LIST_TITLE'); ?></h2>

    <?php if (count($news) > 0): ?>
        <div class="news">
            <ul>
                <?php /** @var $newsItem Llv_Dto_News */ ?>
                <?php foreach ($news as $newsItem): ?>
                <?php $i++; ?>
                <a href="<?= $this->baseUrl(); ?>news/read/id/<?= $newsItem->id; ?>">
                    <li>
                        <div class="left">
                            <?php if (isset($newsItem->illustrations[0])): ?>
                            <img
                                src="<?=
                                    $this->displayImage(
                                        $newsItem->illustrations[0]->filename,
                                        Llv_Constant_File_Category::NEWS,
                                        300,
                                        9999
                                    );
                                    ?>"/>
                            <?php endif; ?>
                            <span class="date">
                                <?= _('NEWS_LIST_DATE_PUBLICATION') ?>
                                <?= $this->dateFormat($newsItem->dateAdd); ?>
                                - <?= _('NEWS_LIST_EN_SAVOIR_PLUS') ?>
                            </span>
                        </div>
                        <div class="right">
                            <h3>
                                <?= $newsItem->title; ?>
                            </h3>

                            <p><?= $this->shortify($newsItem->content, 1000); ?></p>
                        </div>
                    </li>
                </a>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php else: ?>
    <p class='no-result'><?= _('NEWS_LIST_NORESULT'); ?></p>
    <?php endif; ?>
</div>
