<?php
//$module = Llv_Context_Application::getInstance()->getActiveModule();
$this->headLink()->appendStylesheet($this->buildDesignUrl('news/css/element.css'));
$this->headScript()->appendFile($this->buildDesignUrl('news/js/list.js'));
/** @var $spotlight Llv_Dto_News */
$spotlight = $this->spotlight;
$news = $this->news;
$newsPerRow = 3;
$i = 0;
/**  */
$this->headTitle($news->title . ' | ' . _('HEAD_TITLE_NEWS') . ' | ');
?>


<div class="news page">
    <p class="back"><a href="<?= $this->baseUrl(); ?>news"><?= _('GLOBAL_BACK') ?></a></p>

    <h1><?= $news->title ?></h1>

    <div class="contenu"><?= $news->content ?></div>

    <?php if (count($news->illustrations) > 0): ?>
    <h3><?= _('NEWS_ELEMENT_ILLUSTRATION') ?></h3>
    <ul class="illustrations">
        <?php foreach ($news->illustrations as $illustration): ?>
        <li style="background-image: url(<?=$this->displayImage(
            $illustration->filename,
            Llv_Constant_File_Category::NEWS,
            200,
            9999
        );?>)">
            <a href="<?=
                $this->displayImage(
                    $illustration->filename,
                    Llv_Constant_File_Category::NEWS,
                    800,
                    9999
                );
                ?>" rel="colorbox">
                <img
                    src="<?=
                        $this->displayImage(
                            $illustration->filename,
                            Llv_Constant_File_Category::NEWS,
                            200,
                            9999
                        );
                        ?>"/>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
