<?php
//$module = Llv_Context_Application::getInstance()->getActiveModule();
$this->headTitle(_('HEAD_TITLE_NEWS') . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('news/css/element.css'));
$this->headScript()->appendFile($this->buildDesignUrl('news/js/list.js'));
/** @var $spotlight Llv_Dto_News */
$spotlight = $this->spotlight;
$news = $this->news;
$newsPerRow = 3;
$i = 0;
?>


<div class="news">
    <a href="/news"><?= _('GLOBAL_BACK') ?></a>
    <h2><?= $news->title ?></h2>

    <div class="contenu"><?= $news->content ?></div>
    <?php if (count($news->illustrations) > 0): ?>
    <h3><?= _('NEWS_ELEMENT_ILLUSTRATION') ?></h3>
    <ul>
        <?php foreach ($news->illustrations as $illustration): ?>
        <li>
            <a href="<?=
                $this->displayImage(
                    $illustration->filename,
                    Llv_Constant_File_Category::NEWS,
                    800,
                    9999
                );
                ?>" rel="shadowbox[picture]">
                <img
                    src="<?=
                        $this->displayImage(
                            $illustration->filename,
                            Llv_Constant_File_Category::NEWS,
                            200,
                            9999
                        );
                        ?>"/>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
