<?php
$this->headTitle(_('HEAD_TITLE_CONTACT') . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('contact/css/style.css'));
$this->headScript()->appendFile($this->buildDesignUrl('contact/js/index.js'));

$successMessage = $this->successMessage;
$errorMessage = $this->errorMessage;

?>
<div class="page">
    <h1><?= _('CONTACT_TITLE'); ?></h1>
    <ul class="coordonnees">
        <li><?= _('GLOBAL_COORDONNEES_ADRESSE') ?></li>
        <li><?= _('GLOBAL_COORDONNEES_TELEPHONE_LABEL') ?> : <?= _('GLOBAL_COORDONNEES_TELEPHONE') ?></li>
        <li><?= _('GLOBAL_COORDONNEES_MOBILE_LABEL') ?> : <?= _('GLOBAL_COORDONNEES_MOBILE') ?></li>
    </ul>
    <?php if (strlen($successMessage) > 0): ?>
    <ul class='infomessage success'>
        <li><?= $successMessage; ?></li>
    </ul>
    <?php endif; ?>

    <?php if (strlen($errorMessage) > 0): ?>
    <ul class='infomessage error'>
        <li><?= $errorMessage; ?></li>
    </ul>
    <?php endif; ?>

    <?= $this->contactForm; ?>

    <?=
    $this->partial(
        'contact/partial/map.phtml',
        array()
    );
    ?>
</div>