<p>
    <?= _('FOOTER_COPYRIGHT'); ?> - <?= date('Y')?>
    |
    <?= _('FOOTER_CREDITS'); ?> <a href="http://www.aroy.fr">Alexandre ROY</a>
    |
    <a href="<?= $this->url(array('controller'=> 'partners'), null, true);?>"><?= _('FOOTER_PARTENAIRES'); ?></a>
    |
    <a href="<?= $this->url(array('controller'=> 'site-plan'), null, true);?>"><?= _('GLOBAL_MENU_PLAN'); ?></a>
</p>

<p>
    <?= _('GLOBAL_COORDONNEES_ADRESSE'); ?>
    |
    <?= _('GLOBAL_COORDONNEES_TELEPHONE_LABEL'); ?>
    <?= _('GLOBAL_COORDONNEES_TELEPHONE'); ?>
    |
    <?= _('GLOBAL_COORDONNEES_MOBILE_LABEL'); ?>
    <?= _('GLOBAL_COORDONNEES_MOBILE'); ?>
</p>

