<?php
$items = array();
/** Home page */
$items['home'] = array(
    'controller' => 'index',
    'label'      => _('GLOBAL_MENU_HOME')
);
/** Liste des chambres d'hôtes */
$items['chambres'] = array(
    'controller' => 'products',
    'action'     => 'room',
    'args'       => array('type'=>'guesthouse'),
    'label'      => _('GLOBAL_MENU_CHAMBRES')
);
/** Liste des logements du gite */
$items['gite'] = array(
    'controller' => 'products',
    'action'     => 'room',
    'args'       => array('type'=>'chalet'),
    'label'      => _('GLOBAL_MENU_GITE')
);
/** Liste des actualités */
$items['news'] = array(
    'controller' => 'news',
    'label'      => _('GLOBAL_MENU_NEWS')
);
/** Liste des activités */
$items['activities'] = array(
    'controller' => 'activities',
    'label'      => _('GLOBAL_MENU_ACTIVITIES')
);
/** Page de contact */
$items['contact'] = array(
    'controller' => 'contact',
    'label'      => _('GLOBAL_MENU_CONTACT')
);
echo $this->displayMainMenu($items);
echo $this->availableLanguages();
