<?php
$this->headTitle(_('HEAD_TITLE_HOME') . ' | ');
$formActivityEdit = $this->formActivityEdit;
$formFileUploader = $this->formFileUploader;
$this->headLink()->appendStylesheet($this->buildDesignUrl('_common/css/onglets.css'));
$this->headLink()->appendStylesheet($this->buildDesignUrl('activities/css/index.css'));
?>

<div class="page page_cms">
    <h2>
        <?= _('ACTIVITY_EDIT_TITLE') ?>
    </h2>


    <?php if (isset($formFileUploader)): ?>
    <div class="jq-tabs onglets">
        <ul>
            <li>
                <a href="#jq-content"><?php echo _('ACTIVITY_EDIT_TABS_CONTENT'); ?></a>
            </li>
            <li>
                <a href="#jq-pictures"><?php echo _('ACTIVITY_EDIT_TABS_PICTURES'); ?></a>
            </li>
        </ul>
    <?php endif;?>

    <div id="jq-content">
        <?php echo $this->partial('/partial/language_toogler.phtml'); ?>
        <?php echo $formActivityEdit; ?>
    </div>

    <?php if (isset($formFileUploader)): ?>
    <div id="jq-pictures">
        <?php
        echo $this->partial(
            '/activities/partial/illustration.phtml',
            array(
                 'formFileUploader' => $formFileUploader,
                 'illustrations'    => $this->illustrations
            )
        );
        ?>
    </div>
    </div>
    <?php endif;?>
</div>
