<?php
$this->headTitle(_('HEAD_TITLE_ACTIVITY') . ' | ');
$this->headLink()->appendStylesheet($this->buildDesignUrl('carrousel/css/list.css'));
$this->headScript()->appendFile($this->buildDesignUrl('_common/js/jquery.table-action.js'));
$liste = $this->list;
?>

<div class="page page_cms">
    <h2>
        <?= _('ACTIVITY_LIST_TITLE') ?>
    </h2>

    <p class='admin_add'>
        <a href="<?= $this->baseUrl(); ?>activities/edit" title="<?= _('GLOBAL_ADMIN_ADD') ?>">
            <?= _('GLOBAL_ADMIN_ADD') ?>
        </a>
    </p>

    <?php if (count($liste) > 0): ?>
    <table class="list">
        <thead>
        <tr>
            <th><?= _('ACTIVITY_LIST_TITRE')?></th>
            <th><?= _('ACTIVITY_LIST_CATEGORIE')?></th>
            <th><?= _('ACTIVITY_LIST_ONLINE')?></th>
            <th><?= _('GLOBAL_ADMIN_LIST_DATE_AJOUT')?></th>
            <th><?= _('GLOBAL_ADMIN_LIST_DATE_MODIFICATION')?></th>
            <th class="actions"><?= _('GLOBAL_ADMIN_LIST_ACTIONS')?></th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($liste as $ligne): ?>
        <tr>
            <td><?= $ligne->title; ?></td>
            <td><?= $ligne->category->title; ?></td>
            <td><?= $ligne->online ? _('GLOBAL_OUI') : _('GLOBAL_NON'); ?></td>
            <td><?= $this->dateFormat($ligne->dateAdd); ?></td>
            <td><?= $this->dateFormat($ligne->dateUpdate); ?></td>
            <td class="actions">
                <a href="<?= $this->baseUrl(); ?>activities/edit/id/<?= $ligne->id; ?>"
                   class="jq-update update"
                   title="<?= _('GLOBAL_ADMIN_UPDATE') ?>">
                    <?= _('GLOBAL_ADMIN_UPDATE') ?>
                </a>
                <a href="<?= $this->baseUrl(); ?>activities/update/make/delete/id/<?= $ligne->id; ?>"
                   class="jq-delete delete"
                   title="<?= _('GLOBAL_ADMIN_DELETE') ?>">
                    <?= _('GLOBAL_ADMIN_DELETE') ?>
                </a>
                <a href="<?= $this->baseUrl(); ?>activities/update/make/up/id/<?= $ligne->id; ?>"
                   class="moveup"
                   title="<?= _('GLOBAL_ADMIN_UP') ?>">
                    <?= _('GLOBAL_ADMIN_UP') ?>
                </a>
                <a href="<?= $this->baseUrl(); ?>activities/update/make/down/id/<?= $ligne->id; ?>"
                   class="movedown"
                   title="<?= _('GLOBAL_ADMIN_DOWN') ?>">
                    <?= _('GLOBAL_ADMIN_DOWN') ?>
                </a>
            </td>
        </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>
