<?php
$this->headTitle(_('PRODUCTS_EDIT_CATEGORIE_TITLE') . ' | ');
/** @var $formCategoryEdit App_Form_Back_Products_Category */
$formCategoryEdit = $this->formCategoryEdit;
$formFileUploader = $this->formFileUploader;
$this->headLink()->appendStylesheet($this->buildDesignUrl('_common/css/onglets.css'));
$this->headLink()->appendStylesheet($this->buildDesignUrl('products/css/edit-category.css'));
?>

<div class="page page_cms">
    <h2>
        <?= _('PRODUCTS_EDIT_CATEGORIE_TITLE') ?>
        -
        <?= $this->categorie->title ?>
    </h2>


    <?php if (isset($formFileUploader)): ?>
    <div class="jq-tabs onglets">
        <ul>
            <li>
                <a href="#jq-content"><?php echo _('PRODUCTS_EDIT_TABS_CONTENT'); ?></a>
            </li>
            <li>
                <a href="#jq-pictures"><?php echo _('PRODUCTS_EDIT_TABS_PICTURES'); ?></a>
            </li>
        </ul>
    <?php endif;?>

    <div id="jq-content">
        <?php echo $this->partial('/partial/language_toogler.phtml'); ?>
        <?php echo $formCategoryEdit; ?>
    </div>

    <?php if (isset($formFileUploader)): ?>
    <div id="jq-pictures">
        <?=
        $this->partial(
            '/products/partial/illustration-category.phtml',
            array(
                 'formFileUploader' => $formFileUploader,
                 'categorie'    => $this->categorie
            )
        );
        ?>
    </div>
    </div>
    <?php endif;?>
</div>
