<?php
$this->headTitle(_('PRODUCTS_EDIT_PRODUCT_TITLE') . ' | ');
/** @var $formCategoryEdit App_Form_Back_Products_Category */
$formProductEdit = $this->formProductEdit;
$formFileUploader = $this->formFileUploader;
$this->headLink()->appendStylesheet($this->buildDesignUrl('_common/css/onglets.css'));
$this->headLink()->appendStylesheet($this->buildDesignUrl('products/css/edit-product.css'));
?>

<div class="page page_cms">

    <p class="back"><a href="/products/"><?= _('GLOBAL_BACK_SIMPLE') ?></a></p>

    <h2>
        <?= _('PRODUCTS_EDIT_PRODUCT_TITLE') ?>
        -
        <?= $this->product->title ?>
    </h2>


    <?php if (isset($formFileUploader) && isset($this->product)): ?>
    <div class="jq-tabs onglets">
        <ul>
            <li>
                <a href="#jq-content"><?php echo _('PRODUCTS_EDIT_TABS_CONTENT'); ?></a>
            </li>
            <li>
                <a href="#jq-prices"><?php echo _('PRODUCTS_EDIT_TABS_PRICES'); ?></a>
            </li>
            <li>
                <a href="#jq-pictures"><?php echo _('PRODUCTS_EDIT_TABS_PICTURES'); ?></a>
            </li>
        </ul>
    <?php endif;?>

    <div id="jq-content">
        <?php echo $this->partial('/partial/language_toogler.phtml'); ?>
        <?php echo $formProductEdit; ?>
    </div>
    <?php if (isset($this->product)): ?>
    <div id="jq-prices">
        <?php echo $this->formTarif; ?>
    </div>

    <?php if (isset($formFileUploader)): ?>
        <div id="jq-pictures">
            <?=
            $this->partial(
                '/products/partial/illustration-product.phtml',
                array(
                     'formFileUploader' => $formFileUploader,
                     'product'          => $this->product
                )
            );
            ?>
        </div>
    </div>
    <?php endif; ?>
    <?php endif;?>
</div>
