<?php
$this->headTitle(_('HEAD_TITLE_CARROUSEL') . ' | ');
$this->headLink()->appendStylesheet($this->buildDesignUrl('carrousel/css/list.css'));
$this->headScript()->appendFile($this->buildDesignUrl('_common/js/jquery.table-action.js'));
$liste = $this->liste;
?>

<div class="page page_cms">
    <h2>
        <?= _('HOME_CARROUSEL_TITLE') ?>
    </h2>

    <p class='admin_add'>
        <a href="<?= $this->baseUrl(); ?>index/carrousel-add" title="<?= _('GLOBAL_ADMIN_ADD') ?>">
            <?= _('GLOBAL_ADMIN_ADD') ?>
        </a>
    </p>

    <?php if (count($liste) > 0): ?>
    <table class="list">
        <thead>
        <tr>
            <th class="picture"><?= _('GLOBAL_ADMIN_LIST_APERCU')?></th>
            <th><?= _('HOME_CARROUSEL_LIST_ORIGINALFILENAME')?></th>
            <th><?= _('HOME_CARROUSEL_LIST_TYPE')?></th>
            <th><?= _('HOME_CARROUSEL_LIST_ONLINE')?></th>
            <th><?= _('GLOBAL_ADMIN_LIST_DATE_AJOUT')?></th>
            <th><?= _('GLOBAL_ADMIN_LIST_DATE_MODIFICATION')?></th>
            <th class="actions"><?= _('GLOBAL_ADMIN_LIST_ACTIONS')?></th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($liste as $ligne): ?>
        <tr>
            <td class="picture">
                <a href="<?= $this->displayImage($ligne->filename, Llv_Constant_File_Category::CARROUSEL, 800, 600); ?>"
                   rel="shadowbox[picture]">
                    <img
                        src="<?= $this->displayImage($ligne->filename, Llv_Constant_File_Category::CARROUSEL, 100, 75); ?>"/>
                </a>
            </td>
            <td><?= $ligne->originalFilename; ?></td>
            <td><?= $ligne->mimeType; ?></td>
            <td><?= $ligne->online ? _('GLOBAL_OUI') : _('GLOBAL_NON'); ?></td>
            <td><?= $this->dateFormat($ligne->dateAdd); ?></td>
            <td><?= $this->dateFormat($ligne->dateUpdate); ?></td>
            <td class="actions">
                <a href="<?= $this->baseUrl(); ?>index/carrousel-update/make/delete/id/<?= $ligne->id; ?>"
                   class="jq-delete delete"
                   title="<?= _('GLOBAL_ADMIN_DELETE') ?>">
                    <?= _('GLOBAL_ADMIN_DELETE') ?>
                </a>
                <a href="<?= $this->baseUrl(); ?>index/carrousel-update/make/up/id/<?= $ligne->id; ?>"
                   class="moveup"
                   title="<?= _('GLOBAL_ADMIN_UP') ?>">
                    <?= _('GLOBAL_ADMIN_UP') ?>
                </a>
                <a href="<?= $this->baseUrl(); ?>index/carrousel-update/make/down/id/<?= $ligne->id; ?>"
                   class="movedown"
                   title="<?= _('GLOBAL_ADMIN_DOWN') ?>">
                    <?= _('GLOBAL_ADMIN_DOWN') ?>
                </a>
                <?php if ($ligne->online): ?>
                <a href="<?= $this->baseUrl(); ?>index/carrousel-update/make/offline/id/<?= $ligne->id; ?>"
                   class="putoffline"
                   title="<?= _('GLOBAL_ADMIN_OFFLINE') ?>">
                    <?= _('GLOBAL_ADMIN_OFFLINE') ?>
                </a>
                <?php else: ?>
                <a href="<?= $this->baseUrl(); ?>index/carrousel-update/make/online/id/<?= $ligne->id; ?>"
                   class="putonline"
                   title="<?= _('GLOBAL_ADMIN_ONLINE') ?>">
                    <?= _('GLOBAL_ADMIN_ONLINE') ?>
                </a>
                <?php endif; ?>
            </td>
        </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>
