<?php
$items = array();
/** Home page */
$items['home'] = array(
    'controller' => 'index',
    'action'     => 'index',
    'label'      => _('GLOBAL_MENU_HOME'),
    'actions'    => array('index')
);
/** Carrousel */
$items['carrousel'] = array(
    'controller' => 'index',
    'action'     => 'carrousel-list',
    'label'      => _('GLOBAL_MENU_CARROUSEL'),
    'actions'    => array('carrousel-list', 'carrousel-add')
);
/** Liste des actualités */
$items['news'] = array(
    'controller' => 'news',
    'label'      => _('GLOBAL_MENU_NEWS'),
    'actions'    => array('index', 'edit', 'list')
);
/** Liste des activités */
$items['activities'] = array(
    'controller' => 'activities',
    'label'      => _('GLOBAL_MENU_ACTIVITIES'),
    'actions'    => array('index', 'edit', 'list')
);
/** Partenaires */
$items['partners'] = array(
    'controller' => 'index',
    'action'     => 'partners',
    'label'      => _('GLOBAL_MENU_PARTNERS'),
    'actions'    => array('partners')
);
/** Liste des chambres d'hôtes */
$items['location'] = array(
    'controller' => 'products',
    'action'     => 'list',
    'label'      => _('GLOBAL_MENU_LOCATIONS'),
    'actions'    => array('index', 'edit-category', 'edit-product', 'list')
);
/** Liste des logements du gite */
$items['seasons'] = array(
    'controller' => 'season',
    'label'      => _('GLOBAL_MENU_SEASON'),
    'actions'    => array('index', 'edit', 'list')
);
echo $this->displayMainMenu($items);
?>

<p><a href="<?= $this->baseUrl(); ?>index/logout/"><?= _('GLOBAL_MENU_DECONNEXION'); ?></a></p>