<h1><?= _('ERROR_404_TITLE')?></h1>
<p><?= _('ERROR_404_CONTENT')?></p>

<p class="back"><a href="<?= $this->baseUrl(); ?>"><?= _('GLOBAL_BACK_HOME') ?></a></p>

<?php if (APPLICATION_ENV == 'dev'): ?>
    <h3><?php echo $this->message ?></h3>
    <?php if (isset($this->exception)): ?>

        <h3>Exception information:</h3>
        <p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>

    <?php endif; ?>
<?php endif; ?>