<?php
/** @var $category Llv_Dto_Product_Category */
$category = $this->category;
$this->headTitle($category->title . ' | ');
?>
<div class="category">
    <h2><?= $category->title ?> <em>(<?= $category->type ?>)</em></h2>

    <div class="illustration">
        <a href="<?=
        $this->displayImage(
            $category->illustration->filename,
            Llv_Constant_File_Category::PRODUCTS_CATEGORY,
            1000,
            600
        );
        ?>"
           rel="colorbox">
            <img src="<?=
            $this->displayImage(
                $category->illustration->filename,
                Llv_Constant_File_Category::PRODUCTS_CATEGORY,
                450
            );
            ?>"/>
        </a>
    </div>
    <div class="content"><?= $category->content; ?></div>
    <div class="adresse"><?= $category->adresse; ?></div>
</div>
