<?php
/** @var $category Llv_Dto_Product_Category */
$category = $this->category;
$this->headTitle($category->title . ' | ');
?>
<div class="category">
    <?php if (strlen($category->title) > 0 || strlen($category->type) > 0): ?>
    <h1>
        <?php if (strlen($category->title) > 0): ?>
        <?= $category->title ?>
        <?php endif; ?>
        <?php if (strlen($category->type) > 0): ?>
        <em>
            <?= $category->type ?>
        </em>
        <?php endif; ?>
    </h1>
    <?php endif; ?>

    <div class="illustration">
        <a href="<?=
        $this->displayImage(
            $category->illustration->filename,
            Llv_Constant_File_Category::PRODUCTS_CATEGORY,
            1000,
            600
        );
        ?>"
           rel="colorbox">
            <img src="<?=
            $this->displayImage(
                $category->illustration->filename,
                Llv_Constant_File_Category::PRODUCTS_CATEGORY,
                450
            );
            ?>" alt="<?= $category->title ?>"/>
        </a>
    </div>
    <div class="content"><?= $category->content; ?></div>
    <div class="adresse"><?= $category->adresse; ?></div>
</div>


