<?php
$goldbook = $this->goldbook;
$goldbookForm = $this->goldbookForm;
?>

<div id="jq-goldbook" class="goldbook">
    <? if (count($goldbook) > 0): ?>
    <h1><?= _('PRODUCTS_GOLDBOOK_MESSAGES'); ?></h1>
    <ul>
        <? foreach ($goldbook as $message): ?>
        <li>
            <?php if (!is_null($message->dateBegin)): ?>
            <div class="dates">
                <?= _('PRODUCTS_GOLDBOOK_MESSAGES_DATES'); ?> :
                <span><?= _('PRODUCTS_GOLDBOOK_MESSAGES_DATES_DU'); ?></span>
                <strong><?= $this->dateFormat($message->dateBegin);?></strong>
                <span><?= _('PRODUCTS_GOLDBOOK_MESSAGES_DATES_AU'); ?></span>
                <strong><?= $this->dateFormat($message->dateEnd);?></strong>
            </div>
            <? endif; ?>

            <div class="contenu">
                <h3>
                    <?= _('PRODUCTS_GOLDBOOK_MESSAGES_MESSAGE'); ?>
                </h3>

                <p><?= $message->content; ?></p>
            </div>
        </li>
        <? endforeach; ?>
    </ul>
    <? endif; ?>

    <div class="laisser_message">
        <h2><?= _('PRODUCTS_GOLDBOOK_NEW_MESSAGE'); ?></h2>
        <?= $goldbookForm; ?>
    </div>

</div>