<ul>
    <li>
        <a href="#jq-photos"><?php echo _('PRODUCTS_ONGLET_PHOTOS'); ?></a>
    </li>
    <li>
        <a href="#jq-content"><?php echo _('PRODUCTS_ONGLET_CONTENT'); ?></a>
    </li>
    <li>
        <a href="#jq-prices"><?php echo _('PRODUCTS_ONGLET_PRIX'); ?></a>
    </li>
    <!--    <li>-->
    <!--        <a href="#jq-goldbook">--><?php //echo _('NEWS_EDIT_TABS_PICTURES'); ?><!--</a>-->
    <!--    </li>-->
    <li>
        <a href="#jq-reservation"><?php echo _('PRODUCTS_ONGLET_RESERVER'); ?></a>
    </li>
</ul>