<?php
$this->headTitle(_('HEAD_TITLE_HOME') . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('index/css/index.css'));
$this->headScript()->appendFile($this->buildDesignUrl('index/js/index.js'));

$page = $this->page;
?>

<?php
echo $this->partial(
    'index/partial/carrousel.phtml',
    array(
         'carrousel' => $this->carrousel
    )
);
?>

<?php
echo $this->partial(
    'index/partial/news.phtml',
    array(
         'news' => $this->news
    )
);
?>

<div class="presentation">
    <h2>
        <?= $page->title; ?>
    </h2>

    <?= $page->content; ?>

</div>

<?php
echo $this->partial(
    'index/partial/activity.phtml',
    array(
         'activity' => $this->activity
    )
);
?>