<?php
/** @var $product Llv_Dto_Product */
$product = $this->product;
$this->headTitle($product->title . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('products/css/location.css'));
$this->headScript()->appendFile($this->buildDesignUrl('products/js/location.js'));
?>
<div class="page">
    <p class="back"><a href="<?= $this->urlRetour; ?>"><?= _('GLOBAL_BACK') ?></a></p>
    <h2><?= $product->title; ?></h2>
    <div class="introduction"><?= $product->introduction; ?></div>
    <div class="jq-tabs onglets">
        <?=
        $this->partial(
            'products/partial/product/onglets.phtml',
            array(
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/content.phtml',
            array(
                 'product'=> $product
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/photos.phtml',
            array(
                 'product'=> $product
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/prices.phtml',
            array(
                 'product'=> $product
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/reservation.phtml',
            array(
                 'contactForm'=> $this->contactForm
            )
        );
        ?>

    </div>
</div>