<?php
/** @var $product Llv_Dto_Product */
$product = $this->product;
$goldbook = $this->goldbook;
$goldbookForm = $this->goldbookForm;
$contactForm = $this->contactForm;
$this->headTitle($product->title . ' | ' . $product->category->title . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('products/css/location.css'));
$this->headScript()->appendFile($this->buildDesignUrl('products/js/location.js'));
?>
<div class="page">

    <p class="back"><a href="<?= $this->urlRetour; ?>"><?= _('GLOBAL_BACK_SIMPLE') ?></a></p>

    <h2><?= $product->title; ?></h2>

    <div class="introduction"><?= $product->introduction; ?></div>
    <div class="jq-tabs onglets">
        <?=
        $this->partial(
            'products/partial/product/onglets.phtml',
            array(
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/content.phtml',
            array(
                 'product'=> $product
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/photos.phtml',
            array(
                 'product'=> $product
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/prices.phtml',
            array(
                 'product'=> $product
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/goldbook.phtml',
            array(
                 'goldbook'=> $goldbook,
                 'goldbookForm'=> $goldbookForm,
            )
        );
        ?>

        <?=
        $this->partial(
            'products/partial/product/reservation.phtml',
            array(
                 'contactForm'=> $contactForm
            )
        );
        ?>

    </div>
    <p class="back"><a href="<?= $this->urlRetour; ?>"><?= _('GLOBAL_BACK_SIMPLE') ?></a></p>
</div>