<?php
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('products/css/room.css'));
//$this->headScript()->appendFile($this->buildDesignUrl('products/js/room.js'));
?>
<div class="page">
    <?=
    $this->partial(
        'products/partial/category.phtml',
        array(
             'category'=> $this->category
        )
    );
    ?>
    <?=
    $this->partial(
        'products/partial/products.phtml',
        array(
             'products'=> $this->products
        )
    );
    ?>
</div>