<?php
//$module = Llv_Context_Application::getInstance()->getActiveModule();
$this->headTitle(_('HEAD_TITLE_ACTIVITY') . ' | ');
/**  */
$this->headLink()->appendStylesheet($this->buildDesignUrl('activities/css/list.css'));
$this->headScript()->appendFile($this->buildDesignUrl('activities/js/list.js'));
/** @var $spotlight Llv_Dto_News */
//$spotlight = $this->spotlight;
$activities = $this->activities;
$activitiesPerRow = 3;
$i = 0;
?>

<div class="page">
    <h2><?= _('ACTIVITY_LIST_TITLE'); ?></h2>

    <?php if (count($spotlight) == 0 && count($activities) > 0): ?>
    <?php if (count($spotlight) == 1): ?>
        <a href="<?= $this->baseUrl(); ?>activities/read/id/<?= $spotlight->id; ?>">
            <div class="spotlight">
                <div class="left">
                    <?php if (isset($spotlight->illustrations[0])): ?>
                    <img
                        src="<?=
                            $this->displayImage(
                                $spotlight->illustrations[0]->filename,
                                Llv_Constant_File_Category::ACTIVITY,
                                300,
                                9999
                            );
                            ?>"/>
                    <?php endif; ?>
                </div>
                <div class="right">
                    <h3>
                        <?= $spotlight->title; ?>
                    </h3>

                    <p><?= $this->shortify($spotlight->content, 1000); ?></p>
                </div>
            </div>
        </a>
        <?php endif; ?>

    <?php if (count($activities) > 0): ?>
        <div class="activities">
            <ul>
                <?php foreach ($activities as $activity): ?>
                <?php $i++; ?>
                <a href="<?= $this->baseUrl(); ?>activities/read/id/<?= $activity->id; ?>">
                    <li
                        <?php if ($i % 3 == 0): ?>class="no-space"<?php endif; ?>
                            <?php if (isset($activity->illustrations[0])): ?>style="background-image: url(
                        <?=
                        $this->displayImage(
                            $activity->illustrations[0]->filename,
                            Llv_Constant_File_Category::ACTIVITY,
                            400,
                            9999,
                            true
                        )
                        ;?>
                        <?php endif; ?>)">
                            <div class="left">
                                <h3>
                                    <?= $activity->title; ?>
                                </h3>
                            </div>
                    </li>
                </a>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
    <?php else: ?>
    <p class='no-result'><?= _('ACTIVITY_LIST_NORESULT'); ?></p>
    <?php endif; ?>
</div>
