<?php
//$module = Llv_Context_Application::getInstance()->getActiveModule();
$this->headLink()->appendStylesheet($this->buildDesignUrl('activities/css/element.css'));
$this->headScript()->appendFile($this->buildDesignUrl('activities/js/list.js'));
$activity = $this->activity;
/**  */
$this->headTitle($activity->title.' | ' . _('HEAD_TITLE_ACTIVITY') . ' | ');
?>


<div class="activity page">
    <p class="back"><a href="<?= $this->baseUrl(); ?>activities"><?= _('GLOBAL_BACK') ?></a></p>

    <h1><?= $activity->title ?></h1>

    <div class="contenu"><?= $activity->content ?></div>
    <?php if (count($activity->illustrations) > 0): ?>
    <h3><?= _('ACTIVITY_ELEMENT_ILLUSTRATION') ?></h3>
    <ul class="illustrations">
        <?php foreach ($activity->illustrations as $illustration): ?>
        <li style="background-image: url(<?=$this->displayImage(
            $illustration->filename,
            Llv_Constant_File_Category::ACTIVITY,
            200,
            9999
        );?>)">
            <a href="<?=
                $this->displayImage(
                    $illustration->filename,
                    Llv_Constant_File_Category::ACTIVITY,
                    800,
                    9999
                );
                ?>" rel="colorbox">
                <img
                    src="<?=
                        $this->displayImage(
                            $illustration->filename,
                            Llv_Constant_File_Category::ACTIVITY,
                            200,
                            9999
                        );
                        ?>"/>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
