<?php
$this->headScript()->prependFile($this->buildDesignUrl('_plugin/maps/js/googlemaps.js'));
$this->headScript()->prependFile(
    'http://maps.googleapis.com/maps/api/js?key=' . Llv_Config::getInstance()->google->map->key . '&sensor=false'
);
?>
<div class="map">
    <h1><?= _('CONTACT_MAP_TITLE') ?></h1>

    <div id="googlemap"></div>
    <script type="text/javascript">
        var markerList = <?= $this->googlemap();?>;
    </script>
</div>
