<?php
$formFileUploader = $this->formFileUploader;
$categorie = $this->categorie;
?>

<div class="add">
    <?php echo $formFileUploader; ?>
</div>

<ul class="list files">
    <li>
        <a href="<?=
            $this->displayImage(
                $categorie->illustration->filename,
                Llv_Constant_File_Category::PRODUCTS_CATEGORY,
                800,
                600
            );
            ?>"
           rel="shadowbox[picture]">
            <img src="<?=
                $this->displayImage(
                    $categorie->illustration->filename,
                    Llv_Constant_File_Category::PRODUCTS_CATEGORY,
                    195
                );
                ?>"/>
        </a>

</ul>
