<?php
$module = Llv_Context_Application::getInstance()->getActiveModule();
$locale = Llv_Context_Application::getInstance()->getLocale()->toString();
/** @var $this Zend_View */

/** @var $doctype Doctype */
$doctype = new Zend_View_Helper_Doctype();
$doctype->setDoctype('HTML5');

/** Titre du site */
$this->headTitle(_('GLOBAL_HEADER_TITLE'));

/** Metas tags */
$this->headMeta()->setCharset(Llv_Config::getInstance()->project->charset);
$this->headMeta()->appendName('keywords', _('META_KEYWORDS'));
$this->headMeta()->appendName('description', _('META_DESCRIPTION'));
$this->headMeta()->appendName('google-site-verification', _('META_GOOGLE_VERIF'));

/** Feuilles de style */
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/' . $module . '/' . $locale . '/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/' . $module . '/default/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/' . $locale . '/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/default/_common/css/global.css');

/** JS Commun */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/default/default/_common/js/common.js');
/** jQuery */
$this->headScript()->prependFile($this->baseUrl() . 'public/design/default/default/_plugin/jquery.js');
/** jQuery UI */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/default/default/_plugin/jquery-ui/js/jquery.ui.js');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/default/_plugin/jquery-ui/css/style.css');
/** ShadowBox */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/default/default/_plugin/shadowbox/shadowbox.js');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/default/_plugin/shadowbox/shadowbox.css');
/** Colorbox */
$this->headScript()->appendFile($this->baseUrl() . 'public/design/default/default/_plugin/colorbox/jquery.colorbox.js');
$this->headLink()->prependStylesheet($this->baseUrl() . 'public/design/default/default/_plugin/colorbox/colorbox.css');

?>

<?= $this->doctype(); ?>

<html>

<head>

    <?= $this->headTitle(); ?>

    <?= $this->headMeta(); ?>

    <?= $this->headLink(); ?>

    <?= $this->headScript(); ?>

    <script type="text/javascript">
        var i18n = <?= $this->giveJsI18nText();?>;
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-38406329-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>

</head>

<body>

<div id="container">
    <div id="header">
        <?php
        echo $this->partial(
            'partial/header.phtml',
            array()
        );
        ?>
    </div>

    <?php if (Llv_Db::getInstance()->isConnected()) : ?>

    <div id="menu">
        <?php
        echo $this->partial(
            'partial/menu.phtml',
            array()
        );
        ?>
    </div>

    <div id="wrapper"><?= $this->layout()->content; ?></div>

    <?php else : ?>

    <div id="wrapper">
        <?php $this->headTitle(_('HEAD_TITLE_ERROR') . ' | '); ?>
        <?= _('ERROR_DB_CONNECTION'); ?>
    </div>

    <?php endif;?>

    <div id="footer">
        <?php
        echo $this->partial(
            'partial/footer.phtml',
            array()
        );
        ?>
    </div>
</div>


</body>

</html>