<?php
$module = Llv_Context_Application::getInstance()->getActiveModule();
$locale = Llv_Context_Application::getInstance()->getLocale()->toString();
/** @var $this Zend_View */

/** @var $doctype Doctype */
$doctype = new Zend_View_Helper_Doctype();
$doctype->setDoctype('HTML5');

/** Titre du site */
$this->headTitle(_('GLOBAL_HEADER_TITLE'));

/** Metas tags */
$this->headMeta()->setCharset(Llv_Config::getInstance()->project->charset);

/** Feuilles de style */
$this->headLink()->prependStylesheet($this->baseUrl() . 'design/' . $module . '/' . $locale . '/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'design/' . $module . '/default/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'design/default/' . $locale . '/_common/css/global.css');
$this->headLink()->prependStylesheet($this->baseUrl() . 'design/default/default/_common/css/global.css');

/** JS Commun */
$this->headScript()->appendFile($this->baseUrl() . 'design/default/default/_common/js/common.js');
/** jQuery */
$this->headScript()->prependFile($this->baseUrl() . 'design/default/default/_plugin/jquery.js');
/** jQuery UI */
$this->headScript()->appendFile($this->baseUrl() . 'design/default/default/_plugin/jquery-ui/js/jquery.ui.js');
$this->headLink()->prependStylesheet($this->baseUrl() . 'design/default/default/_plugin/jquery-ui/css/style.css');
/** ShadowBox */
$this->headScript()->appendFile($this->baseUrl() . 'design/default/default/_plugin/shadowbox/shadowbox.js');
$this->headLink()->prependStylesheet($this->baseUrl() . 'design/default/default/_plugin/shadowbox/shadowbox.css');

?>

<?= $this->doctype(); ?>

<html>

<head>

    <?= $this->headTitle(); ?>

    <?= $this->headMeta(); ?>

    <?= $this->headLink(); ?>

    <?= $this->headScript(); ?>

</head>

<body>

<div id="container">
    <div id="header">
        <?php
        echo $this->partial(
            'partial/header.phtml',
            array()
        );
        ?>
    </div>

    <?php if (Llv_Db::getInstance()->isConnected()) : ?>

    <div id="menu">
        <?php
        echo $this->partial(
            'partial/menu.phtml',
            array()
        );
        ?>
    </div>

    <div id="wrapper"><?= $this->layout()->content; ?></div>

    <?php else : ?>

    <div id="wrapper">
        <?php $this->headTitle(_('HEAD_TITLE_ERROR') . ' | '); ?>
        <?= _('ERROR_DB_CONNECTION'); ?>
    </div>

    <?php endif;?>

    <div id="footer">
        <?php
        echo $this->partial(
            'partial/footer.phtml',
            array()
        );
        ?>
    </div>
</div>
<script type="text/javascript">
    var i18n = <?= $this->giveJsI18nText();?>;
</script>

</body>

</html>