<?php
$module = Llv_Context_Application::getInstance()->getActiveModule();
$locale = Llv_Context_Application::getInstance()->getLocale()->toString();
/** @var $this Zend_View */

/** @var $doctype Doctype */
$doctype = new Zend_View_Helper_Doctype();
$doctype->setDoctype('HTML5');

/** Titre du site */
$this->headTitle('Luchon Location Vacances');

/** Metas tags */
$this->headMeta()->setCharset(Llv_Config::getInstance()->project->charset);

/** Feuilles de style */
$this->headLink()->appendStylesheet($this->baseUrl() . '/design/default/default/css/reset.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/design/default/default/css/global.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/design/default/' . $locale . '/css/global.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/design/' . $module . '/' . $locale . '/css/global.css');

?>
<?php echo $this->doctype(); ?>

<html>

<head>

    <?php echo $this->headTitle(); ?>

    <?php echo $this->headMeta(); ?>

    <?php echo $this->headLink(); ?>

    <?php echo $this->headScript(); ?>

</head>

<body>

<div id="container">
    <div id="header">
        <?php
            echo $this->partial(
                'partial/header.phtml',
                array()
            );
        ?>
    </div>

    <div id="menu">
        <?php
        echo $this->partial(
            'partial/menu.phtml',
            array()
        );
        ?>
    </div>

    <div id="wrapper"><?php echo $this->layout()->content; ?></div>

    <div id="footer">
        <?php
        echo $this->partial(
            'partial/footer.phtml',
            array()
        );
        ?>
    </div>
</div>

</body>

</html>